version: '2'
services:
  web:
    build: web-server/
    ports:
      - "8000:80"
    networks:
      ssrf:
        ipv4_address: 10.0.0.2
  internal:
    build: internal/
    networks:
      ssrf:
        ipv4_address: 10.0.0.3
networks:
  ssrf:
    ipam:
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1